# FROM node:20
FROM ubuntu:rolling

WORKDIR /app/main

RUN apt-get update && apt-get install -y nodejs npm

COPY package*.json ./

RUN npm install --production --silent

COPY . .

ENV SERVER_PORT="server:8080"

CMD ["bash"]